[package]
name = "generate_html"
version = "0.1.0"
authors = ["lazypassion <25536767+lazypassion@users.noreply.github.com>"]
edition = "2018"

[dependencies]
typed-html = "0.2.0"
horrorshow = "0.6.6"
pulldown-cmark = "0.4.0"